export class Column {
  name: string;
  type: string;
  nullable: boolean;
  isKey: boolean;
  isAutoGenerated: boolean;

  constructor(name: string, type: string, nullable: boolean, isKey: boolean, isAutoGenerated: boolean) {
    this.name = name;
    this.type = type;
    this.nullable = nullable;
    this.isKey = isKey;
    this.isAutoGenerated = isAutoGenerated;
  }
}
