export class Column {
  name: string;
  type: string;
  nullable: boolean;
  isKey: boolean;
  isAutoGenerated: boolean;
  defaultValue: string;

  constructor(
    name: string,
    type: string,
    nullable: boolean,
    isKey: boolean,
    isAutoGenerated: boolean,
    defaultValue: string
  ) {
    this.name = name;
    this.type = type;
    this.nullable = nullable;
    this.isKey = isKey;
    this.isAutoGenerated = isAutoGenerated;
    this.defaultValue = defaultValue;
  }
}
