import {Component, Input} from '@angular/core';
import {TableDescriptionService} from "../../services/table-description.service";
import {Column} from "../../model/column";
import {InputTypePipe} from "../../pipes/input-type-pipe";
import {DbManagerService} from "../../services/db-manager.service";
import {FormControl, FormGroup, ReactiveFormsModule, Validators} from "@angular/forms";

@Component({
  selector: 'app-insert-view',
  standalone: true,
  imports: [
    InputTypePipe,
    ReactiveFormsModule
  ],
  templateUrl: './insert-view.component.html',
  styleUrl: './insert-view.component.css'
})
export class InsertViewComponent {
  @Input() schema = '';
  @Input() table = '';
  columns: Column[] = [];
  insertForm : FormGroup = new FormGroup({});

  constructor(
    private tableDescription: TableDescriptionService,
    private manager: DbManagerService
  ) {
    this.tableDescription.columns.subscribe(
      (response) => {
        this.columns = response;
        let groupControls: Record<string, FormControl> = {};
        for (let column of this.columns) {
          groupControls[column.name] = new FormControl(
            '',
            (column.nullable && !column.isAutoGenerated) ?
              Validators.required : Validators.nullValidator
          );
        }
        this.insertForm = new FormGroup(groupControls);
      }
    );
  }

  onSubmit() {
    console.warn(this.insertForm.value);
  }
}
